name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yaml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Doppler
        uses: dopplerhq/cli-action@v2
        with:
          doppler-token: ${{ secrets.DOPPLER_BACKEND_TOKEN }}

      - name: Download .env from Doppler
        run: doppler secrets download --no-file --format env > .env
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_BACKEND_TOKEN }}

      - name: Move and cat .env
        run: |
          mv .env ./backend/.env
          cat ./backend/.env

      - name: Build Backend Docker image
        run: docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/primary-repository/classfellow-api ./backend

      - name: Push Backend Docker image
        run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/primary-repository/classfellow-api

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy classfellow-api \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/primary-repository/classfellow-api \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --port=5500
